name: Publish Website
run-name: Publishing Website
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - docs/website/**

jobs:
  website:
    name: Build Website
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Dependencies
      run: make website-setup
    - name: Build Website
      run: make website-build
    - uses: gardener/cc-utils/.github/actions/upload-artifact@master
      with:
        name: website
        path: website-out

  publish-website:
    if: >-
      ${{ github.ref_name == github.event.repository.default_branch  &&
          github.repository == 'open-delivery-gear/open-delivery-gear'
      }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - website
    steps:
      - uses: actions/checkout@v4
        with:
          ref: refs/heads/website
      - name: Setup Git Identity
        uses: gardener/cc-utils/.github/actions/setup-git-identity@master
      - name: Retrieve Website
        uses: gardener/cc-utils/.github/actions/download-artifact@master
        with:
          name: website
          path: /tmp/website-out
      - name: Publish Website
        run: |
          # Remove all existing files except .git and .nojekyll
          find . -maxdepth 1 ! -name '.git' ! -name '.nojekyll' ! -name '.' ! -name '..' -exec rm -rf {} +

          # Extract website content
          tar c -C /tmp/website-out . | tar x -C.

          # Ensure .nojekyll exists
          touch .nojekyll

          git status
          if [ -z "$(git status --porcelain)" ]; then
            echo "no changes in website - no need to update"
            exit 0
          fi
          git add -A
          git commit -m "Update website"
          git push origin refs/heads/website
