name: Build Website

on:
  workflow_call:

jobs:
  website:
    name: Build Website
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Dependencies
      run: make website-setup
    - name: Build Website
      run: make website-build
    - uses: gardener/cc-utils/.github/actions/upload-artifact@v1
      with:
        name: website
        path: website-out
